CREATE TABLE NW_USER (
     ID SERIAL PRIMARY KEY,
     USER_NAME VARCHAR(100) NULL,
     USER_TYPE VARCHAR(100) NULL,
     ROLES VARCHAR(500) NULL,
     AUTH VARCHAR(500) NULL,
     MOD_USR VARCHAR(30) DEFAULT current_user NULL,
     MOD_DAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
     CRE_USR VARCHAR(30) DEFAULT current_user NULL,
     CRE_DAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
     ACTIVE BOOLEAN NOT NULL
);